### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by SpaceK33z** [styled-components/babel-plugin-styled-components#12]
Currently all CSS used in styled-components is unminified.
As @mxstbr suggested on Gitter, this Babel plugin could take care of minifying the CSS.
Perhaps only when `process.env.NODE_ENV === 'production'`?

Alternatively, this could be a [babili](https://github.com/babel/babili) plugin.

Related to https://github.com/styled-components/styled-components/issues/284

**Comment by mxstbr** [comment]
That could totally work, shouldn't be too hard actually with the base we already have! I haven't looked too deep into it, but doing `s/\s/` on the CSS should kinda just work? What do you think @vdanchenkov?

**Comment by vdanchenkov** [comment]
It would be hard to cover all cases due to interpolations, but we definitely could support some basic stuff. `s/\s/` (trim whitespace from the beginning of each line) should work fine. Maybe we could make it little more advanced like this: http://cssnano.co/optimisations/core/

**Comment by mxstbr** [comment]
True, good point about the dev! Let's try making this happen then?

**Comment by vdanchenkov** [comment]
I'll look into it tomorrow. Will minify css`` and styled.x``.

**Comment by kopax** [comment]
any update on that topic?

**Comment by vdanchenkov** [comment]
We can dramatically reduce css-related code by removing template literals

```jsx
const Test1 = styled.div`
  width: 100%;
`;

// transpiles with babel-plugin-transform-es2015-template-literals to

function _taggedTemplateLiteral(strings, raw) { 
  return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); 
}
var _templateObject = _taggedTemplateLiteral(['\n  width: 100%;\n  color: ', ';\n'], ['\n  width: 100%;\n  color: ', ';\n']),
var Test1 = _styledComponents2.default.div(_templateObject, color);
```

As far as I can see we do not use `raw` values, so it could be transpiled with our plugin to:
```jsx
var Test1 = _styledComponents2.default.div(['\n  width: 100%;\n  color: ', ';\n'], color);

// or with minification

var Test1 = _styledComponents2.default.div(['width: 100%;color: ', ';'], color);
```

@mxstbr Am I correct that it will work as is with styled-components lib?

**Comment by mxstbr** [comment]
`raw` is a publicly accessible API that babel plugins can hook into (`node.value.raw`, see [the spec](https://github.com/babel/babylon/blob/master/ast/spec.md#templateelement)) so I doubt we can just remove it!

What we should instead do is get rid of all the whitespace in the template literals and let everybody transpile them (or not transpile them if they only support Chrome) however they want?

**Comment by vdanchenkov** [comment]
It's actually two cases but they are related.

Simple whitespace removal could be done, but it looks like a lot of work with little benefit. Typically it will remove 3 characters per rule if we remove newlines and spaces at the start of every line. We can not safely remove all whitespaces due to cases like `content: "  ${value}  "; `

The problem with template literals is that we need to remove whitespace from both raw and cooked values and strategies are little different. For example, in `raw` we have weird things like `\\n` and '\n' both representing line-break. We can even come to situation where raw and cooked values diverge significantly due to minification. That is why I don't like the idea of minifying two values separately. It would be cleaner if we minify raw and convert to cooked after minification, but I'm not sure about edge cases here.

My suggestion is similar to replacement of template literal with private API, but it can be done with no changes in the lib, I guess. I suggest to replace template literal node with regular function call.

It will give over 50% reduction of footprint if transpilation will be applied. But will slightly increase footprint if no transpilation is needed (4 chars per template literal, +1 per interpolation).

**Comment by vdanchenkov** [comment]
@SpaceK33z Could you check #15 with your test cases? You can paste examples of your code to fixture 08-minify-css-to-use-with-transpilation if you transpile template literals or 09-minify-css-to-use-without-transpilation if not. Run npm test to check it's output.

**Comment by SpaceK33z** [comment]
@vdanchenkov, looks good! I tested some code from a small project with it. I don't have much code since I was still evaluating styled-components, but it worked. It looks like keyframes aren't compressed however (red = expected, green = actual):

```diff
-const sweep = keyframes`to {transform: rotate(360deg);}`;
+const sweep = keyframes`
+    to {
+        transform: rotate(360deg);
+    }
+`;
```

**Comment by mxstbr** [comment]
> My suggestion is similar to replacement of template literal with private API, but it can be done with no changes in the lib, I guess. I suggest to replace template literal node with regular function call.

> It will give over 50% reduction of footprint if transpilation will be applied. But will slightly increase footprint if no transpilation is needed (4 chars per template literal, +1 per interpolation).

Let's do this then!

**Comment by SpaceK33z** [comment]
Thanks @vdanchenkov for fixing this, really awesome :).
