### ISSUE TITLE
Doesn't work with create-react-app (pre-eject)

### ISSUE THREAD

**Issue by chriswhawkins** [styled-components/babel-plugin-styled-components#59]
Thanks so much for everyone's hard work on this amazing `styled-components` ecosystem.

I have a small component library that I set up using `create-react-app` and `styled-components` and could not get this plugin to work at all without doing an `npm run eject` and then it worked exactly as advertised.

Has anyone else experienced this or, more importantly, figured out a way to get the plugin working without ejecting? This is probably more of a `create-react-app` issue, but given the popularity of it, it would be nice to have a solution and/or a note about it not working in this Readme.

Thanks again!

**Comment by philpl** [comment]
This might be able to help you :) https://github.com/withspectrum/react-app-rewire-styled-components

**Comment by mattpelosi** [comment]
I'm having a similar problem with getting the plugin working.

Let's say I've just created a boilerplate create-react-app and run npm install for the styled components library.  What are the specific steps I need to take in order to get the babel-plugin-styled-components plugin working?

I've followed the plugin documentation on this procedure. I've run an eject, then npm installed the plugin, created a .babelrc file, copied the settings from the documentation into it,  and then restarted the app. No luck, the correct component names don't appear in the React Dev Tools. I'm missing something here.

**Comment by chriswhawkins** [comment]
@mattpelosi instead of creating a .babelrc file, try adding the plugin and any options you want into your `package.json` file:
```
...
  "babel": {
    "plugins": [
      ["babel-plugin-styled-components"]
    ],
    "presets": [
      "react-app"
    ]
  },
...
```

**Comment by probablyup** [comment]
Looks like you solved it!

**Comment by adamchenwei** [comment]
nop, its not working

**Comment by chriswhawkins** [comment]
@adamchenwei, the solution I posted above is actually for a post eject scenario. If you're trying to get this to work in a pre-ejected create-react-app, you'll want to use [react-app-rewired](https://github.com/timarney/react-app-rewired) with [react-app-rewire-styled-components](https://github.com/withspectrum/react-app-rewire-styled-components).

**Comment by adamchenwei** [comment]
@chriswhawkins ok, thanks for the info! 👍

**Comment by probablyup** [comment]
@progressbear starting with v4 we ship a babel macro so you don't have to do that: https://www.styled-components.com/docs/tooling#babel-macro

**Comment by renatocarvalho** [comment]
@probablyup This solved my problems! Thank you!

**Comment by probablyup** [comment]
Because if you don't have the babel macro stuff set up in your build system it'd error out?

**Comment by akshaygoyal88** [comment]
Styles are not working in production build while using famous html2canvas plugin https://html2canvas.hertzen.com/
