### ISSUE TITLE
Preprocessing mangling css 

### ISSUE THREAD

**Issue by silverlight513** [styled-components/babel-plugin-styled-components#65]
I've got the following code using styled-components, polished and a media query function based on the one specified in the styled-components docs (https://www.styled-components.com/docs/advanced#media-templates).

```
const Wrapper = styled.div`
  ${clearFix()}
  margin-top: ${rem('10px')};

  ${media.bpSmall`
    margin-top: 0;
  `}
`;
```

When using the babel-plugin on the following settings:
```    
["styled-components", {
  "ssr": true,
  "preprocess": false,
  "minify": false
}]
```

It works perfectly fine and I get the expected output:
```
/* sc-component-id: Header__Wrapper-ceoji3-0 */
.Header__Wrapper-ceoji3-0 {}

.BXvSp{margin-top: 0.625rem;}.BXvSp::after{clear: both;content: "";display: table;}@media (min-width: 34.375rem){.BXvSp{margin-top: 0;}}
```

When turning on preprocessing I get the following output:
```
/* sc-component-id: Header__Wrapper-ceoji3-0 */
.Header__Wrapper-ceoji3-0 {}

.lfbwyd{&::after {
  clear: both; content: ""; display: table;
};margin-top: 0.625rem;;}.lfbwyd@media (min-width: 34.375rem){.lfbwyd{
    margin-top: 0;
  ;}}
```

I've got more examples of similar breaks if it would be helpful.

`babel-plugin-styled-components@1.1.5`
`styled-components@2.0.1`
`polished@1.1.3`

**Comment by philpl** [comment]
Thanks for the report, as discussed on twitter DMs :)

Do you mind including the babel output of the js file containing the component that is being incorrectly preprocessed?

**Comment by silverlight513** [comment]
Thanks for the quick response!

Wrapping styles in the css helper did fix a problem where values weren't being returned (on other components) but I'm not sure it's done anything to help parsing in a this case.

I've updated the component to look like this
```
const Wrapper = styled.div`
  ${css`${clearFix()}`}
  margin-top: ${css`${rem('10px')}`};

  ${media.bpSmall(css`
    margin-top: 0;
  `)}
`;
```

It's now outputting:
```
/* sc-component-id: Header__Wrapper-s1pjgzvd-0 */
.Header__Wrapper-s1pjgzvd-0 {}

.lhoWrm{;margin-top: ;;}.lhoWrm{&::after {
  clear: both; content: ""; display: table;
};}.lhoWrm{0.625rem;}.lhoWrm@media (min-width: 34.375rem){.lhoWrm{;}}.lhoWrm{margin-top: 0;}
```

**Comment by philpl** [comment]
Ok, so this is not doing anything. You have to wrap the return value of the clearfix function in `css`.

`css` is meant to be used for mixins. This means that any block of css in any interpolation needs to be parsable at **build time**. So this means whatever you return in `clearFix` needs to return its css inside the `css` helper.

E.g.:

```js
const clearFix = () => css`some css...`
```

The media helper is looking fine, assuming you update `media.bpSmall` **not** to accept all args, but to be sth like:

```
const bpSmall = mixin => css`
  @media (max-width: 1000px) {
    ${mixin}
  }
```

Then it of course just inlines the mixin, which is wrapped outside inside `css`.

The `rem` output on the other hand must not to be wrapped, since it's a value.
