### ISSUE TITLE
Conflict with 'babel-plugin-add-react-displayname'

### ISSUE THREAD

**Issue by chhuang** [styled-components/babel-plugin-styled-components#67]
This works (it shows the component's name):

```
  "plugins": [
    [
      "styled-components", {
        "ssr": true
      },

      "add-react-displayname"
    ]
```

This doesn't:
```
  "plugins": [
    [
      "add-react-displayname",

      "styled-components", {
        "ssr": true
      }
    ]
```

**Comment by philpl** [comment]
It's likely a bug with their plugin, since with SC we're not giving the plugin any components to target. I'm not quite sure what it even does and how it works, but I'm pretty sure you won't even need it.

So for SC we have our own `displayName` option.

For functions as pure functional components, the devtools are going to display the function name as the component name: `function ComponentName () {...}`

For arrow functions you'll have to bind them to a variable and the function will infer its function name to be the variable name: `const ComponentName = () => null`

And for classes it'll just display ... well ... its name.

So I'm not really sure why you'd need it, but i'd suspect that it's at fault here. Some babel output would help though, if you'd like me to help track this down ;)
