### ISSUE TITLE
Deduplicate rules when using extend

### ISSUE THREAD

**Issue by probablyup** [styled-components/babel-plugin-styled-components#68]
Feel free to close this if I'm wrong, but it seems like when a styled component is extended, the new styles are simply appended to the end of the original styles. 

It would be cool if this babel plugin could dedupe staticly defined properties that have multiple instances within the same styling context.

**Comment by philpl** [comment]
It's impossible to do this, since we don't have access to all parents and mixins during the runtime. So I'm going with the Proof of concept preprocessing concept and building on it for v3. One that doesn't make any assumptions and makes it unnecessary to "break out" of a css context that needs to be processed.

For the ISTF standard I wrote down a summary which should make it clear why we can't do this: https://gist.github.com/philpl/1099bf4a4a28ced28dbb6b204c5fdcb3

It's possible at runtime but we want to get rid of the overhead there
